[tool.poetry]
name = "demo"
version = "0.1.0"
description = "Demo application to showcase the Arcane Development Kit"
authors = ["Marco lamina <marco@arcane.engineer>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.1.1"
arcane-engine = "^1.8.0"
pygithub = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
